/* eslint-disable */
/**
 * This file was automatically generated by @algorandfoundation/algokit-client-generator.
 * DO NOT MODIFY IT BY HAND.
 * requires: @algorandfoundation/algokit-utils: ^7
 */
import { type AlgorandClient } from '@algorandfoundation/algokit-utils/types/algorand-client'
import { ABIReturn, AppReturn, SendAppTransactionResult } from '@algorandfoundation/algokit-utils/types/app'
import { Arc56Contract, getArc56ReturnValue, getABIStructFromABITuple } from '@algorandfoundation/algokit-utils/types/app-arc56'
import {
  AppClient as _AppClient,
  AppClientMethodCallParams,
  AppClientParams,
  AppClientBareCallParams,
  CallOnComplete,
  AppClientCompilationParams,
  ResolveAppClientByCreatorAndName,
  ResolveAppClientByNetwork,
  CloneAppClientParams,
} from '@algorandfoundation/algokit-utils/types/app-client'

import { TransactionComposer, AppCallMethodCall, AppMethodCallTransactionArgument, SimulateOptions, RawSimulateOptions, SkipSignaturesSimulateOptions } from '@algorandfoundation/algokit-utils/types/composer'
import { SendParams, SendSingleTransactionResult, SendAtomicTransactionComposerResults } from '@algorandfoundation/algokit-utils/types/transaction'
import { Address, encodeAddress, modelsv2, OnApplicationComplete, Transaction, TransactionSigner } from 'algosdk'

export const APP_SPEC: Arc56Contract = {"arcs":[],"name":"DuplicateStructs","desc":"\n    Used for snapshot testing to ensure no duplicate struct definitions in typed clients.\n    ","structs":{"SomeStruct":[{"name":"a","type":"uint64"},{"name":"b","type":"uint64"}]},"methods":[{"name":"method_a_that_uses_struct","args":[],"returns":{"type":"(uint64,uint64)","struct":"SomeStruct"},"events":[],"actions":{"create":[],"call":["NoOp"]}},{"name":"method_b_that_uses_same_struct","args":[],"returns":{"type":"(uint64,uint64)","struct":"SomeStruct"},"events":[],"actions":{"create":[],"call":["NoOp"]}}],"state":{"schema":{"global":{"ints":0,"bytes":0},"local":{"ints":0,"bytes":0}},"keys":{"global":{},"local":{},"box":{}},"maps":{"global":{},"local":{},"box":{}}},"bareActions":{"create":["NoOp"],"call":[]}} as unknown as Arc56Contract

/**
 * A state record containing binary data
 */
export interface BinaryState {
  /**
   * Gets the state value as a Uint8Array
   */
  asByteArray(): Uint8Array | undefined
  /**
   * Gets the state value as a string
   */
  asString(): string | undefined
}

class BinaryStateValue implements BinaryState {
  constructor(private value: Uint8Array | undefined) {}

  asByteArray(): Uint8Array | undefined {
    return this.value
  }

  asString(): string | undefined {
    return this.value !== undefined ? Buffer.from(this.value).toString('utf-8') : undefined
  }
}

/**
 * Expands types for IntelliSense so they are more human readable
 * See https://stackoverflow.com/a/69288824
 */
export type Expand<T> = T extends (...args: infer A) => infer R
  ? (...args: Expand<A>) => Expand<R>
  : T extends infer O
    ? { [K in keyof O]: O[K] }
    : never


// Type definitions for ARC-56 structs

export type SomeStruct = {
  a: bigint,
  b: bigint
}


/**
 * Converts the ABI tuple representation of a SomeStruct to the struct representation
 */
export function SomeStructFromTuple(abiTuple: [bigint, bigint]) {
  return getABIStructFromABITuple(abiTuple, APP_SPEC.structs.SomeStruct, APP_SPEC.structs) as SomeStruct
}

/**
 * The argument types for the DuplicateStructs contract
 */
export type DuplicateStructsArgs = {
  /**
   * The object representation of the arguments for each method
   */
  obj: {
    'method_a_that_uses_struct()(uint64,uint64)': Record<string, never>
    'method_b_that_uses_same_struct()(uint64,uint64)': Record<string, never>
  }
  /**
   * The tuple representation of the arguments for each method
   */
  tuple: {
    'method_a_that_uses_struct()(uint64,uint64)': []
    'method_b_that_uses_same_struct()(uint64,uint64)': []
  }
}

/**
 * The return type for each method
 */
export type DuplicateStructsReturns = {
  'method_a_that_uses_struct()(uint64,uint64)': SomeStruct
  'method_b_that_uses_same_struct()(uint64,uint64)': SomeStruct
}

/**
 * Defines the types of available calls and state of the DuplicateStructs smart contract.
 */
export type DuplicateStructsTypes = {
  /**
   * Maps method signatures / names to their argument and return types.
   */
  methods:
    & Record<'method_a_that_uses_struct()(uint64,uint64)' | 'method_a_that_uses_struct', {
      argsObj: DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)']
      argsTuple: DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']
      returns: DuplicateStructsReturns['method_a_that_uses_struct()(uint64,uint64)']
    }>
    & Record<'method_b_that_uses_same_struct()(uint64,uint64)' | 'method_b_that_uses_same_struct', {
      argsObj: DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)']
      argsTuple: DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']
      returns: DuplicateStructsReturns['method_b_that_uses_same_struct()(uint64,uint64)']
    }>
}

/**
 * Defines the possible abi call signatures.
 */
export type DuplicateStructsSignatures = keyof DuplicateStructsTypes['methods']
/**
 * Defines the possible abi call signatures for methods that return a non-void value.
 */
export type DuplicateStructsNonVoidMethodSignatures = keyof DuplicateStructsTypes['methods'] extends infer T ? T extends keyof DuplicateStructsTypes['methods'] ? MethodReturn<T> extends void ? never : T  : never : never
/**
 * Defines an object containing all relevant parameters for a single call to the contract.
 */
export type CallParams<TArgs> = Expand<
  Omit<AppClientMethodCallParams, 'method' | 'args' | 'onComplete'> &
    {
      /** The args for the ABI method call, either as an ordered array or an object */
      args: Expand<TArgs>
    }
>
/**
 * Maps a method signature from the DuplicateStructs smart contract to the method's arguments in either tuple or struct form
 */
export type MethodArgs<TSignature extends DuplicateStructsSignatures> = DuplicateStructsTypes['methods'][TSignature]['argsObj' | 'argsTuple']
/**
 * Maps a method signature from the DuplicateStructs smart contract to the method's return type
 */
export type MethodReturn<TSignature extends DuplicateStructsSignatures> = DuplicateStructsTypes['methods'][TSignature]['returns']



/**
 * Exposes methods for constructing `AppClient` params objects for ABI calls to the DuplicateStructs smart contract
 */
export abstract class DuplicateStructsParamsFactory {
  /**
   * Constructs a no op call for the method_a_that_uses_struct()(uint64,uint64) ABI method
   *
   * @param params Parameters for the call
   * @returns An `AppClientMethodCallParams` object for the call
   */
  static methodAThatUsesStruct(params: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete {
    return {
      ...params,
      method: 'method_a_that_uses_struct()(uint64,uint64)' as const,
      args: Array.isArray(params.args) ? params.args : [],
    }
  }
  /**
   * Constructs a no op call for the method_b_that_uses_same_struct()(uint64,uint64) ABI method
   *
   * @param params Parameters for the call
   * @returns An `AppClientMethodCallParams` object for the call
   */
  static methodBThatUsesSameStruct(params: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']> & CallOnComplete): AppClientMethodCallParams & CallOnComplete {
    return {
      ...params,
      method: 'method_b_that_uses_same_struct()(uint64,uint64)' as const,
      args: Array.isArray(params.args) ? params.args : [],
    }
  }
}

/**
 * A client to make calls to the DuplicateStructs smart contract
 */
export class DuplicateStructsClient {
  /**
   * The underlying `AppClient` for when you want to have more flexibility
   */
  public readonly appClient: _AppClient

  /**
   * Creates a new instance of `DuplicateStructsClient`
   *
   * @param appClient An `AppClient` instance which has been created with the DuplicateStructs app spec
   */
  constructor(appClient: _AppClient)
  /**
   * Creates a new instance of `DuplicateStructsClient`
   *
   * @param params The parameters to initialise the app client with
   */
  constructor(params: Omit<AppClientParams, 'appSpec'>)
  constructor(appClientOrParams: _AppClient | Omit<AppClientParams, 'appSpec'>) {
    this.appClient = appClientOrParams instanceof _AppClient ? appClientOrParams : new _AppClient({
      ...appClientOrParams,
      appSpec: APP_SPEC,
    })
  }

  /**
   * Checks for decode errors on the given return value and maps the return value to the return type for the given method
   * @returns The typed return value or undefined if there was no value
   */
  decodeReturnValue<TSignature extends DuplicateStructsNonVoidMethodSignatures>(method: TSignature, returnValue: ABIReturn | undefined) {
    return returnValue !== undefined ? getArc56ReturnValue<MethodReturn<TSignature>>(returnValue, this.appClient.getABIMethod(method), APP_SPEC.structs) : undefined
  }

  /**
   * Returns a new `DuplicateStructsClient` client, resolving the app by creator address and name
   * using AlgoKit app deployment semantics (i.e. looking for the app creation transaction note).
   * @param params The parameters to create the app client
   */
  public static async fromCreatorAndName(params: Omit<ResolveAppClientByCreatorAndName, 'appSpec'>): Promise<DuplicateStructsClient> {
    return new DuplicateStructsClient(await _AppClient.fromCreatorAndName({...params, appSpec: APP_SPEC}))
  }
  
  /**
   * Returns an `DuplicateStructsClient` instance for the current network based on
   * pre-determined network-specific app IDs specified in the ARC-56 app spec.
   *
   * If no IDs are in the app spec or the network isn't recognised, an error is thrown.
   * @param params The parameters to create the app client
   */
  static async fromNetwork(
    params: Omit<ResolveAppClientByNetwork, 'appSpec'>
  ): Promise<DuplicateStructsClient> {
    return new DuplicateStructsClient(await _AppClient.fromNetwork({...params, appSpec: APP_SPEC}))
  }
  
  /** The ID of the app instance this client is linked to. */
  public get appId() {
    return this.appClient.appId
  }
  
  /** The app address of the app instance this client is linked to. */
  public get appAddress() {
    return this.appClient.appAddress
  }
  
  /** The name of the app. */
  public get appName() {
    return this.appClient.appName
  }
  
  /** The ARC-56 app spec being used */
  public get appSpec() {
    return this.appClient.appSpec
  }
  
  /** A reference to the underlying `AlgorandClient` this app client is using. */
  public get algorand(): AlgorandClient {
    return this.appClient.algorand
  }

  /**
   * Get parameters to create transactions for the current app. A good mental model for this is that these parameters represent a deferred transaction creation.
   */
  readonly params = {
    /**
     * Makes a clear_state call to an existing instance of the DuplicateStructs smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.params.bare.clearState(params)
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_a_that_uses_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call params
     */
    methodAThatUsesStruct: (params: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.params.call(DuplicateStructsParamsFactory.methodAThatUsesStruct(params))
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_b_that_uses_same_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call params
     */
    methodBThatUsesSameStruct: (params: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.params.call(DuplicateStructsParamsFactory.methodBThatUsesSameStruct(params))
    },

  }

  /**
   * Create transactions for the current app
   */
  readonly createTransaction = {
    /**
     * Makes a clear_state call to an existing instance of the DuplicateStructs smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams>) => {
      return this.appClient.createTransaction.bare.clearState(params)
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_a_that_uses_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call transaction
     */
    methodAThatUsesStruct: (params: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.createTransaction.call(DuplicateStructsParamsFactory.methodAThatUsesStruct(params))
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_b_that_uses_same_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call transaction
     */
    methodBThatUsesSameStruct: (params: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      return this.appClient.createTransaction.call(DuplicateStructsParamsFactory.methodBThatUsesSameStruct(params))
    },

  }

  /**
   * Send calls to the current app
   */
  readonly send = {
    /**
     * Makes a clear_state call to an existing instance of the DuplicateStructs smart contract.
     *
     * @param params The params for the bare (raw) call
     * @returns The clearState result
     */
    clearState: (params?: Expand<AppClientBareCallParams & SendParams>) => {
      return this.appClient.send.bare.clearState(params)
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_a_that_uses_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call result
     */
    methodAThatUsesStruct: async (params: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']> & SendParams & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      const result = await this.appClient.send.call(DuplicateStructsParamsFactory.methodAThatUsesStruct(params))
      return {...result, return: result.return as unknown as (undefined | DuplicateStructsReturns['method_a_that_uses_struct()(uint64,uint64)'])}
    },

    /**
     * Makes a call to the DuplicateStructs smart contract using the `method_b_that_uses_same_struct()(uint64,uint64)` ABI method.
     *
     * @param params The params for the smart contract call
     * @returns The call result
     */
    methodBThatUsesSameStruct: async (params: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']> & SendParams & {onComplete?: OnApplicationComplete.NoOpOC} = {args: []}) => {
      const result = await this.appClient.send.call(DuplicateStructsParamsFactory.methodBThatUsesSameStruct(params))
      return {...result, return: result.return as unknown as (undefined | DuplicateStructsReturns['method_b_that_uses_same_struct()(uint64,uint64)'])}
    },

  }

  /**
   * Clone this app client with different params
   *
   * @param params The params to use for the the cloned app client. Omit a param to keep the original value. Set a param to override the original value. Setting to undefined will clear the original value.
   * @returns A new app client with the altered params
   */
  public clone(params: CloneAppClientParams) {
    return new DuplicateStructsClient(this.appClient.clone(params))
  }

  /**
   * Methods to access state for the current DuplicateStructs app
   */
  state = {
  }

  public newGroup(): DuplicateStructsComposer {
    const client = this
    const composer = this.algorand.newGroup()
    let promiseChain:Promise<unknown> = Promise.resolve()
    const resultMappers: Array<undefined | ((x: ABIReturn | undefined) => any)> = []
    return {
      /**
       * Add a method_a_that_uses_struct()(uint64,uint64) method call against the DuplicateStructs contract
       */
      methodAThatUsesStruct(params: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC}) {
        promiseChain = promiseChain.then(async () => composer.addAppCallMethodCall(await client.params.methodAThatUsesStruct(params)))
        resultMappers.push((v) => client.decodeReturnValue('method_a_that_uses_struct()(uint64,uint64)', v))
        return this
      },
      /**
       * Add a method_b_that_uses_same_struct()(uint64,uint64) method call against the DuplicateStructs contract
       */
      methodBThatUsesSameStruct(params: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']> & {onComplete?: OnApplicationComplete.NoOpOC}) {
        promiseChain = promiseChain.then(async () => composer.addAppCallMethodCall(await client.params.methodBThatUsesSameStruct(params)))
        resultMappers.push((v) => client.decodeReturnValue('method_b_that_uses_same_struct()(uint64,uint64)', v))
        return this
      },
      /**
       * Add a clear state call to the DuplicateStructs contract
       */
      clearState(params: AppClientBareCallParams) {
        promiseChain = promiseChain.then(() => composer.addAppCall(client.params.clearState(params)))
        return this
      },
      addTransaction(txn: Transaction, signer?: TransactionSigner) {
        promiseChain = promiseChain.then(() => composer.addTransaction(txn, signer))
        return this
      },
      async composer() {
        await promiseChain
        return composer
      },
      async simulate(options?: SimulateOptions) {
        await promiseChain
        const result = await (!options ? composer.simulate() : composer.simulate(options))
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      },
      async send(params?: SendParams) {
        await promiseChain
        const result = await composer.send(params)
        return {
          ...result,
          returns: result.returns?.map((val, i) => resultMappers[i] !== undefined ? resultMappers[i]!(val) : val.returnValue)
        }
      }
    } as unknown as DuplicateStructsComposer
  }
}
export type DuplicateStructsComposer<TReturns extends [...any[]] = []> = {
  /**
   * Calls the method_a_that_uses_struct()(uint64,uint64) ABI method.
   *
   * @param args The arguments for the contract call
   * @param params Any additional parameters for the call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  methodAThatUsesStruct(params?: CallParams<DuplicateStructsArgs['obj']['method_a_that_uses_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_a_that_uses_struct()(uint64,uint64)']>): DuplicateStructsComposer<[...TReturns, DuplicateStructsReturns['method_a_that_uses_struct()(uint64,uint64)'] | undefined]>

  /**
   * Calls the method_b_that_uses_same_struct()(uint64,uint64) ABI method.
   *
   * @param args The arguments for the contract call
   * @param params Any additional parameters for the call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  methodBThatUsesSameStruct(params?: CallParams<DuplicateStructsArgs['obj']['method_b_that_uses_same_struct()(uint64,uint64)'] | DuplicateStructsArgs['tuple']['method_b_that_uses_same_struct()(uint64,uint64)']>): DuplicateStructsComposer<[...TReturns, DuplicateStructsReturns['method_b_that_uses_same_struct()(uint64,uint64)'] | undefined]>

  /**
   * Makes a clear_state call to an existing instance of the DuplicateStructs smart contract.
   *
   * @param args The arguments for the bare call
   * @returns The typed transaction composer so you can fluently chain multiple calls or call execute to execute all queued up transactions
   */
  clearState(params?: AppClientBareCallParams): DuplicateStructsComposer<[...TReturns, undefined]>

  /**
   * Adds a transaction to the composer
   *
   * @param txn A transaction to add to the transaction group
   * @param signer The optional signer to use when signing this transaction.
   */
  addTransaction(txn: Transaction, signer?: TransactionSigner): DuplicateStructsComposer<TReturns>
  /**
   * Returns the underlying AtomicTransactionComposer instance
   */
  composer(): Promise<TransactionComposer>
  /**
   * Simulates the transaction group and returns the result
   */
  simulate(): Promise<DuplicateStructsComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: SkipSignaturesSimulateOptions): Promise<DuplicateStructsComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  simulate(options: RawSimulateOptions): Promise<DuplicateStructsComposerResults<TReturns> & { simulateResponse: modelsv2.SimulateResponse }>
  /**
   * Sends the transaction group to the network and returns the results
   */
  send(params?: SendParams): Promise<DuplicateStructsComposerResults<TReturns>>
}
export type DuplicateStructsComposerResults<TReturns extends [...any[]]> = Expand<SendAtomicTransactionComposerResults & {
  returns: TReturns
}>

