import { DocumentParts, inline, NewLine } from '../output/writer'
import { AlgoAppSpec } from '../schema/application'
import { callFactory } from './call-factory'
import { callClient } from './call-client'
import { deployTypes } from './deploy-types'
import { utilityTypes } from './utility-types'
import { imports } from './imports'
import { createGeneratorContext, GeneratorOptions } from './generator-context'
import { appTypes } from './app-types'
import { callComposerType } from './call-composer-types'
import { IdentifierNaming } from '../util/sanitization'

export function* generate(app: AlgoAppSpec, options: GeneratorOptions = { identifierNames: IdentifierNaming.JavaScript }): DocumentParts {
  const ctx = createGeneratorContext(app, options)
  yield `/* eslint-disable */`
  yield `/**`
  yield ` * This file was automatically generated by @algorandfoundation/algokit-client-generator.`
  yield ` * DO NOT MODIFY IT BY HAND.`
  yield ` * requires: @algorandfoundation/algokit-utils: ^2`
  yield ` */`

  yield* imports()
  yield* inline('export const APP_SPEC: AppSpec = ', JSON.stringify(app, undefined, 2))
  yield NewLine

  yield* utilityTypes()
  yield NewLine
  yield* appTypes(ctx)
  yield* deployTypes(ctx)
  yield NewLine

  // Write a call factory
  yield* callFactory(ctx)
  yield NewLine
  // Write a client
  yield* callClient(ctx)

  yield* callComposerType(ctx)
}
