import { DocumentParts, inline, NewLine } from '../output/writer'
import { paramsFactory } from './params-factory'
import { appClient } from './app-client'
import { deployTypes } from './deploy-types'
import { utilityTypes } from './utility-types'
import { imports } from './imports'
import { createGeneratorContext, GeneratorOptions } from './generator-context'
import { appTypes } from './app-types'
import { callComposerType } from './call-composer-types'
import { Arc56Contract, StructField } from '@algorandfoundation/algokit-utils/types/app-arc56'
import { appFactory } from './app-factory'
import { Sanitizer } from '../util/sanitization'

function convertStructs(s: StructField[], sanitizer: Sanitizer): StructField[] {
  return s.map(
    ({ name, type }) =>
      ({
        name: sanitizer.makeSafePropertyIdentifier(name),
        type: typeof type === 'string' ? type : convertStructs(type, sanitizer),
      }) satisfies StructField,
  )
}

function stripSourceInfo(app: Arc56Contract): Arc56Contract {
  const strippedApp = { ...app } as Arc56Contract & {
    source?: { approval: string; clear: string }
    byteCode?: { approval: string; clear: string }
  }

  if (strippedApp.sourceInfo?.approval?.sourceInfo) {
    // Keep only source info entries that have errorMessage
    strippedApp.sourceInfo.approval.sourceInfo = strippedApp.sourceInfo.approval.sourceInfo
      .filter((entry) => entry.errorMessage !== undefined)
      .map((entry) => ({
        pc: entry.pc,
        errorMessage: entry.errorMessage!,
        // Keep minimal context for error mapping if available
        ...(entry.teal !== undefined && { teal: entry.teal }),
      }))
  }

  if (strippedApp.sourceInfo?.clear?.sourceInfo) {
    // Apply same logic to clear program source info
    strippedApp.sourceInfo.clear.sourceInfo = strippedApp.sourceInfo.clear.sourceInfo
      .filter((entry) => entry.errorMessage !== undefined)
      .map((entry) => ({
        pc: entry.pc,
        errorMessage: entry.errorMessage!,
        ...(entry.teal !== undefined && { teal: entry.teal }),
      }))
  }

  // Remove approval and clear programs to reduce size
  // These are needed for deployment but not for calling existing contracts
  if (strippedApp.source) {
    delete strippedApp.source
  }
  if (strippedApp.byteCode) {
    delete strippedApp.byteCode
  }

  return strippedApp
}

export function* generate(app: Arc56Contract, options: GeneratorOptions = { preserveNames: false }): DocumentParts {
  // Apply source info stripping if slim mode is enabled
  const processedApp = options.slim ? stripSourceInfo(app) : app

  const ctx = createGeneratorContext(processedApp, options)
  yield `/* eslint-disable */`
  yield `/**`
  yield ` * This file was automatically generated by @algorandfoundation/algokit-client-generator.`
  yield ` * DO NOT MODIFY IT BY HAND.`
  yield ` * requires: @algorandfoundation/algokit-utils: ^7`
  yield ` */`

  yield* imports()
  // Change the structs definition to sanitize property names according to the defined rules
  // for instance, this may (unless you passed in --preserve-names) convert properties like my_prop to myProp
  processedApp.structs = Object.fromEntries(
    Object.keys(processedApp.structs).map((key) => [key, convertStructs(processedApp.structs[key], ctx.sanitizer)]),
  )
  yield* inline('export const APP_SPEC: Arc56Contract = ', JSON.stringify(processedApp), ' as unknown as Arc56Contract')
  yield NewLine

  yield* utilityTypes()
  yield NewLine
  yield* appTypes(ctx)

  // Only generate deploy types if not in slim mode
  if (!ctx.slim) {
    yield* deployTypes(ctx)
  }
  yield NewLine

  // Write a call factory
  yield* paramsFactory(ctx)
  yield NewLine
  // Write a factory
  yield* appFactory(ctx)
  // Write a client
  yield* appClient(ctx)

  yield* callComposerType(ctx)
}
