name: Prod Publish

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  prod_release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge main -> release
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f
        with:
          type: now
          from_branch: main
          target_branch: release
          github_token: ${{ steps.app_token.outputs.token }}
      - name: Merge release -> main
        uses: devmasx/merge-branch@854d3ac71ed1e9deb668e0074781b81fdd6e771f
        with:
          type: now
          from_branch: release
          target_branch: main
          message: Merge release back to main to get version increment [no ci]
          github_token: ${{ steps.app_token.outputs.token }}
      - name: Trigger Publish
        run: gh workflow run 'Publish' --ref release
        env:
          GH_TOKEN: ${{ github.token }}
